export const languages: { [key: string]: string } = {
  AR: "Arabic",
  CS: "Czech",
  CY: "Welsh",
  DA: "Danish",
  DE: "German",
  EL: "Greek",
  EN: "English",
  ES: "Spanish",
  ET: "Estonian",
  FA: "Persian",
  FI: "Finnish",
  FIL: "Filipino",
  FR: "French",
  GA: "Irish",
  GU: "Gujarati",
  HE: "Hebrew",
  HI: "Hindi",
  HR: "Croatian",
  HU: "Hungarian",
  HY: "Armenian",
  ID: "Indonesian",
  IS: "Icelandic",
  IT: "Italian",
  JA: "Japanese",
  KA: "Georgian",
  KK: "Kazakh",
  KM: "Khmer",
  KN: "Kannada",
  KO: "Korean",
  KU: "Kurdish",
  KY: "Kyrgyz",
  LN: "Lingala",
  LO: "Lao",
  LT: "Lithuanian",
  LV: "Latvian",
  MAI: "Maithili",
  MG: "Malagasy",
  MI: "Māori",
  MK: "Macedonian",
  ML: "Malayalam",
  MN: "Mongolian",
  MS: "Malay",
  MT: "Maltese",
  MY: "Myanmar (Burmese)",
  NB: "Norwegian",
  NE: "Nepali",
  NL: "Dutch",
  PA: "Punjabi",
  PL: "Polish",
  PT: "Portuguese (Brazil)",
  RO: "Romanian",
  RU: "Russian",
  SK: "Slovak",
  SL: "Slovenian",
  SM: "Samoan",
  SO: "Somali",
  SQ: "Albanian",
  "SR-Cyrl": "Serbian (Cyrillic)",
  "SR-Latn": "Serbian (Latin)",
  SV: "Swedish",
  SW: "Swahili",
  TA: "Tamil",
  TE: "Telugu",
  TH: "Thai",
  TI: "Tigrinya",
  TK: "Turkmen",
  TN: "Setswana",
  TO: "Tongan",
  TR: "Turkish",
  TT: "Tatar",
  TY: "Tahitian",
  UG: "Uyghur",
  UK: "Ukrainian",
  UR: "Urdu",
  UZ: "Uzbek (Latin)",
  VI: "Vietnamese",
  ZHS: "Chinese Simplified",
  ZHT: "Chinese Traditional",
  ZU: "Zulu",
};
